apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsphere-cloud-controller-manager
rules:
# vSphere has a separate node manager that uses the serivce account kube-system/vsphere-cloud-controller-manager
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
