apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nutanix-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch

