apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nutanix-cloud-controller-manager:nutanix-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
roleRef:
  kind: Role
  name: nutanix-cloud-controller-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: cloud-provider-nutanix
