apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nutanix-cloud-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
