apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .someLabel }}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        k8s-app: {{ .someLabel }}
    spec:
      containers:
      - args:
        - -v=2
        image: {{ .images.Foo }}
        imagePullPolicy: IfNotPresent
        name: cloud-controller-manager
