apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cloud-node-manager
  namespace: openshift-cloud-controller-manager
  labels:
    component: azure-cloud-node-manager
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: azure-cloud-node-manager
  template:
    metadata:
      labels:
        app: azure-cloud-node-manager
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cloud-node-manager
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
      containers:
        - name: cloud-node-manager
          image: quay.io/openshift/origin-azure-cloud-node-manager:4.8.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -o allexport
              if [[ -f /etc/kubernetes/apiserver-url.env ]]; then
                source /etc/kubernetes/apiserver-url.env
              fi
              exec /bin/azure-cloud-node-manager \
                --node-name=$(NODE_NAME) \
                --wait-routes=false \
                --use-instance-metadata=false \
                --cloud-config=$(CLOUD_CONFIG) \
                --v=6
          ports:
          - containerPort: 10263
            name: https
            protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AZURE_ENVIRONMENT_FILEPATH
              value: /etc/kubernetes-cloud-config/endpoints.conf
            - name: CLOUD_CONFIG
              value: /etc/kubernetes-cloud-config/cloud.conf
          volumeMounts:
            - name: host-etc-kube
              mountPath: /etc/kubernetes
              readOnly: true
            - name: config-accm
              mountPath: /etc/kubernetes-cloud-config
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: host-etc-kube
          hostPath:
            path: /etc/kubernetes
            type: Directory
        - name: config-accm
          configMap:
            name: cloud-conf
            items:
              - key: cloud.conf
                path: cloud.conf
              - key: endpoints
                path: endpoints.conf
