apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: cloud-controller-manager
  annotations:
    capability.openshift.io/name: CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: config.openshift.io
      name: cloud-controller-manager
      resource: clusteroperators
    - group: ""
      name: openshift-cloud-controller-manager
      resource: namespaces
    - group: ""
      name: openshift-cloud-controller-manager-operator
      resource: namespaces
