apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-nutanix-cloud-controller-manager
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: CloudCredential+CloudControllerManager
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  secretRef:
    name: nutanix-credentials
    namespace: openshift-cloud-controller-manager
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: NutanixProviderSpec
